import type { LeadDetail, Operator } from './types'

// Reference: "now" is around Mar 2, 2026 18:00 IST
function hoursAgo(h: number): string {
  const d = new Date('2026-03-02T18:00:00+05:30')
  d.setHours(d.getHours() - h)
  return d.toISOString()
}

function daysAgo(d: number): string {
  return hoursAgo(d * 24)
}

function daysFromNow(d: number): string {
  const dt = new Date('2026-03-02T18:00:00+05:30')
  dt.setDate(dt.getDate() + d)
  return dt.toISOString()
}

const ops: Record<number, Operator[]> = {
  14: [
    { id: 101, lead_id: 14, operator_name: 'Sharma Travels', vehicle_number: 'MH-04-AB-1234', operator_amount: 18000, toll_amount: 500, toll_receipt: null, parking_amount: 200, driver_allowances: 500, extra_km_charges: 0, other_charges: 0, remark: null, modified: daysAgo(1) },
  ],
  15: [
    { id: 102, lead_id: 15, operator_name: 'Patel Tours', vehicle_number: 'MH-01-CD-5678', operator_amount: 35000, toll_amount: 1200, toll_receipt: 'yes', parking_amount: 400, driver_allowances: 800, extra_km_charges: 2000, other_charges: 500, remark: 'Extra stop at Lonavala', modified: daysAgo(3) },
    { id: 103, lead_id: 15, operator_name: 'Patel Tours', vehicle_number: 'MH-01-CD-9012', operator_amount: 32000, toll_amount: 1200, toll_receipt: 'yes', parking_amount: 400, driver_allowances: 800, extra_km_charges: 0, other_charges: 0, remark: 'Second bus', modified: daysAgo(3) },
  ],
  16: [
    { id: 104, lead_id: 16, operator_name: 'Gupta Transport', vehicle_number: 'MH-02-EF-3456', operator_amount: 22000, toll_amount: 800, toll_receipt: null, parking_amount: 300, driver_allowances: 600, extra_km_charges: 0, other_charges: 300, remark: 'Water bottles', modified: daysAgo(0) },
  ],
  17: [],
  // New converted leads operators
  26: [
    { id: 105, lead_id: 26, operator_name: 'Rebello', vehicle_number: 'MH04LQ2670', operator_amount: 25000, toll_amount: 900, toll_receipt: 'yes', parking_amount: 300, driver_allowances: 600, extra_km_charges: 0, other_charges: 0, remark: null, modified: daysAgo(2) },
  ],
  27: [
    { id: 106, lead_id: 27, operator_name: 'Surya Travels', vehicle_number: 'MH43BX5349', operator_amount: 14000, toll_amount: 400, toll_receipt: null, parking_amount: 200, driver_allowances: 400, extra_km_charges: 0, other_charges: 200, remark: null, modified: daysAgo(1) },
  ],
  28: [
    { id: 107, lead_id: 28, operator_name: 'Indian Travels', vehicle_number: 'DD01Y9580', operator_amount: 42000, toll_amount: 1500, toll_receipt: 'yes', parking_amount: 500, driver_allowances: 1000, extra_km_charges: 3000, other_charges: 0, remark: 'Overnight parking at hotel', modified: daysAgo(4) },
    { id: 108, lead_id: 28, operator_name: 'Indian Travels', vehicle_number: 'DD01R9500', operator_amount: 40000, toll_amount: 1500, toll_receipt: 'yes', parking_amount: 500, driver_allowances: 1000, extra_km_charges: 0, other_charges: 0, remark: 'Second bus', modified: daysAgo(4) },
  ],
  29: [
    { id: 109, lead_id: 29, operator_name: 'GHAPL', vehicle_number: 'MH04LE2927', operator_amount: 8000, toll_amount: 200, toll_receipt: null, parking_amount: 0, driver_allowances: 300, extra_km_charges: 0, other_charges: 0, remark: null, modified: daysAgo(0) },
  ],
  30: [
    { id: 110, lead_id: 30, operator_name: 'Dwarikamai', vehicle_number: 'MH02GH6877', operator_amount: 16000, toll_amount: 600, toll_receipt: null, parking_amount: 200, driver_allowances: 500, extra_km_charges: 0, other_charges: 0, remark: null, modified: daysAgo(3) },
  ],
  31: [
    { id: 111, lead_id: 31, operator_name: 'Ajara Travels', vehicle_number: 'MH01EM9799', operator_amount: 55000, toll_amount: 2000, toll_receipt: 'yes', parking_amount: 800, driver_allowances: 1200, extra_km_charges: 5000, other_charges: 500, remark: 'Multi-day with driver stay', modified: daysAgo(5) },
  ],
  32: [
    { id: 112, lead_id: 32, operator_name: 'Siddhant Travels', vehicle_number: 'DD01Y9477', operator_amount: 20000, toll_amount: 700, toll_receipt: null, parking_amount: 300, driver_allowances: 500, extra_km_charges: 0, other_charges: 0, remark: null, modified: daysAgo(1) },
  ],
  33: [],
}

export const DUMMY_LEADS: LeadDetail[] = [
  // === OPEN — fresh ===
  {
    id: 1, source_table: 'App', prod_id: 50001, name: 'Amit Deshmukh', mobile_number: '9876543210', email: 'amit.d@gmail.com',
    origin: 'Andheri East, Mumbai', destination: 'Pune Airport', start_date_time: daysFromNow(5), end_date_time: daysFromNow(5),
    number_of_passengers: 4, additional_comment: 'Need AC bus', source: 'app', travel_distance: '150 km', travel_time: '3h',
    vehicle_type_requirement: 'Sedan', status: 'Open', reason: null, internal_remarks: null,
    amount_quote: null, amount_cityflo: null, amount_operator: null, operator_name: null,
    created: hoursAgo(3), modified: hoursAgo(3), created_by_email_id: null,
    assigned_to_email_id: 'vaibhavi.salvi@cityflo.com', lead_type: 'one-way', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },
  {
    id: 2, source_table: 'Web', prod_id: 50002, name: 'Sneha Kulkarni', mobile_number: '9123456789', email: 'sneha.k@outlook.com',
    origin: 'Bandra West, Mumbai', destination: 'Nashik Vineyards', start_date_time: daysFromNow(10), end_date_time: daysFromNow(11),
    number_of_passengers: 8, additional_comment: 'Corporate outing, need Tempo Traveller', source: 'website', travel_distance: '170 km', travel_time: '3.5h',
    vehicle_type_requirement: 'Tempo Traveller', status: 'Open', reason: null, internal_remarks: null,
    amount_quote: null, amount_cityflo: null, amount_operator: null, operator_name: null,
    created: hoursAgo(6), modified: hoursAgo(6), created_by_email_id: null,
    assigned_to_email_id: 'priya.mehta@cityflo.com', lead_type: 'round-trip', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },

  // === OPEN — stale (>24h) ===
  {
    id: 3, source_table: 'Meta', prod_id: 50003, name: 'Rakesh Joshi', mobile_number: '9988776655', email: null,
    origin: 'Thane Station', destination: 'Shirdi Temple', start_date_time: daysFromNow(4), end_date_time: daysFromNow(4),
    number_of_passengers: 6, additional_comment: null, source: 'Meta', travel_distance: '240 km', travel_time: '5h',
    vehicle_type_requirement: 'Innova', status: 'Open', reason: null, internal_remarks: null,
    amount_quote: null, amount_cityflo: null, amount_operator: null, operator_name: null,
    created: hoursAgo(30), modified: hoursAgo(30), created_by_email_id: null,
    assigned_to_email_id: 'vaibhavi.salvi@cityflo.com', lead_type: 'round-trip', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },
  {
    id: 4, source_table: 'Meta', prod_id: 50004, name: 'Fatima Sheikh', mobile_number: '9871234567', email: 'fatima.s@yahoo.com',
    origin: 'Dadar TT, Mumbai', destination: 'Mahabaleshwar', start_date_time: daysFromNow(7), end_date_time: daysFromNow(8),
    number_of_passengers: 12, additional_comment: 'Family trip with kids, need spacious vehicle', source: 'Meta', travel_distance: '260 km', travel_time: '5.5h',
    vehicle_type_requirement: 'Mini Bus', status: 'Open', reason: null, internal_remarks: null,
    amount_quote: null, amount_cityflo: null, amount_operator: null, operator_name: null,
    created: daysAgo(2), modified: daysAgo(2), created_by_email_id: null,
    assigned_to_email_id: 'rahul.gupta@cityflo.com', lead_type: 'round-trip', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },
  {
    id: 5, source_table: 'App', prod_id: 50005, name: 'Vikram Malhotra', mobile_number: '9765432100', email: 'vikram.m@gmail.com',
    origin: 'Powai, Mumbai', destination: 'Alibaug Beach', start_date_time: daysFromNow(2), end_date_time: daysFromNow(2),
    number_of_passengers: 5, additional_comment: 'Weekend getaway', source: 'app', travel_distance: '100 km', travel_time: '2.5h',
    vehicle_type_requirement: 'Innova Crysta', status: 'Open', reason: null, internal_remarks: null,
    amount_quote: null, amount_cityflo: null, amount_operator: null, operator_name: null,
    created: daysAgo(3), modified: daysAgo(3), created_by_email_id: null,
    assigned_to_email_id: 'priya.mehta@cityflo.com', lead_type: 'round-trip', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },

  // === OPEN — urgent (trip very soon) ===
  {
    id: 21, source_table: 'App', prod_id: 50021, name: 'Deepak Nair', mobile_number: '9654321098', email: 'deepak.n@company.com',
    origin: 'BKC, Mumbai', destination: 'Lonavala Resort', start_date_time: daysFromNow(1), end_date_time: daysFromNow(1),
    number_of_passengers: 10, additional_comment: 'Team outing TOMORROW, urgent!', source: 'direct call', travel_distance: '85 km', travel_time: '2h',
    vehicle_type_requirement: 'Tempo Traveller', status: 'Open', reason: null, internal_remarks: null,
    amount_quote: null, amount_cityflo: null, amount_operator: null, operator_name: null,
    created: hoursAgo(4), modified: hoursAgo(4), created_by_email_id: null,
    assigned_to_email_id: 'vaibhavi.salvi@cityflo.com', lead_type: 'round-trip', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },

  // === CONTACTED — fresh ===
  {
    id: 6, source_table: 'Web', prod_id: 50006, name: 'Pooja Reddy', mobile_number: '9845612378', email: 'pooja.r@gmail.com',
    origin: 'Juhu, Mumbai', destination: 'Goa (Panjim)', start_date_time: daysFromNow(14), end_date_time: daysFromNow(16),
    number_of_passengers: 6, additional_comment: 'Need luxury vehicle for wedding guests', source: 'website', travel_distance: '590 km', travel_time: '10h',
    vehicle_type_requirement: 'Luxury Bus', status: 'Contacted', reason: null, internal_remarks: 'Called, interested. Will discuss with family.',
    amount_quote: null, amount_cityflo: null, amount_operator: null, operator_name: null,
    created: daysAgo(2), modified: hoursAgo(5), created_by_email_id: null,
    assigned_to_email_id: 'vaibhavi.salvi@cityflo.com', lead_type: 'round-trip', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },
  {
    id: 7, source_table: 'Meta', prod_id: 50007, name: 'Suresh Patil', mobile_number: '9912345678', email: null,
    origin: 'Borivali, Mumbai', destination: 'Igatpuri', start_date_time: daysFromNow(6), end_date_time: daysFromNow(6),
    number_of_passengers: 15, additional_comment: null, source: 'Meta', travel_distance: '130 km', travel_time: '2.5h',
    vehicle_type_requirement: 'Tempo Traveller', status: 'Contacted', reason: null, internal_remarks: 'WhatsApp message sent, seen but no reply yet',
    amount_quote: null, amount_cityflo: null, amount_operator: null, operator_name: null,
    created: daysAgo(1), modified: hoursAgo(18), created_by_email_id: null,
    assigned_to_email_id: 'rahul.gupta@cityflo.com', lead_type: 'one-way', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },

  // === CONTACTED — stale (>48h no quote) ===
  {
    id: 8, source_table: 'App', prod_id: 50008, name: 'Manisha Desai', mobile_number: '9834567890', email: 'manisha.d@hotmail.com',
    origin: 'Vashi, Navi Mumbai', destination: 'Kolhapur', start_date_time: daysFromNow(8), end_date_time: daysFromNow(9),
    number_of_passengers: 4, additional_comment: 'Temple visit', source: 'app', travel_distance: '380 km', travel_time: '7h',
    vehicle_type_requirement: 'Innova', status: 'Contacted', reason: null, internal_remarks: 'Spoke on phone, asked for quote. Haven\'t sent yet.',
    amount_quote: null, amount_cityflo: null, amount_operator: null, operator_name: null,
    created: daysAgo(4), modified: daysAgo(3), created_by_email_id: null,
    assigned_to_email_id: 'vaibhavi.salvi@cityflo.com', lead_type: 'round-trip', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },
  {
    id: 9, source_table: 'Meta', prod_id: 50009, name: 'Arun Menon', mobile_number: '9776543210', email: 'arun.m@techcorp.in',
    origin: 'Worli, Mumbai', destination: 'Lavasa', start_date_time: daysFromNow(3), end_date_time: daysFromNow(4),
    number_of_passengers: 20, additional_comment: 'Corporate retreat, need 2 buses', source: 'Meta', travel_distance: '185 km', travel_time: '4h',
    vehicle_type_requirement: 'Bus (2)', status: 'Contacted', reason: null, internal_remarks: 'High value lead. MD\'s office called directly.',
    amount_quote: null, amount_cityflo: null, amount_operator: null, operator_name: null,
    created: daysAgo(5), modified: daysAgo(4), created_by_email_id: null,
    assigned_to_email_id: 'priya.mehta@cityflo.com', lead_type: 'round-trip', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },

  // === CONTACTED — trip very soon ===
  {
    id: 22, source_table: 'App', prod_id: 50022, name: 'Kavita Sharma', mobile_number: '9543216789', email: 'kavita@gmail.com',
    origin: 'Malad, Mumbai', destination: 'Khandala', start_date_time: daysFromNow(1), end_date_time: daysFromNow(2),
    number_of_passengers: 8, additional_comment: null, source: 'referral', travel_distance: '80 km', travel_time: '2h',
    vehicle_type_requirement: 'Tempo Traveller', status: 'Contacted', reason: null, internal_remarks: 'Referred by existing customer. Trip is tomorrow!',
    amount_quote: null, amount_cityflo: null, amount_operator: null, operator_name: null,
    created: daysAgo(1), modified: hoursAgo(20), created_by_email_id: null,
    assigned_to_email_id: 'rahul.gupta@cityflo.com', lead_type: 'round-trip', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },

  // === QUOTE SHARED — fresh ===
  {
    id: 10, source_table: 'Web', prod_id: 50010, name: 'Nitin Agarwal', mobile_number: '9887654321', email: 'nitin.a@enterprise.com',
    origin: 'Lower Parel, Mumbai', destination: 'Pune (Hinjewadi IT Park)', start_date_time: daysFromNow(5), end_date_time: daysFromNow(5),
    number_of_passengers: 30, additional_comment: 'Daily employee shuttle trial', source: 'website', travel_distance: '150 km', travel_time: '3h',
    vehicle_type_requirement: 'Bus 32-seater', status: 'Quote Shared', reason: null, internal_remarks: 'Shared quote for monthly contract. Decision by Friday.',
    amount_quote: 85000, amount_cityflo: 75000, amount_operator: null, operator_name: null,
    created: daysAgo(3), modified: hoursAgo(8), created_by_email_id: null,
    assigned_to_email_id: 'vaibhavi.salvi@cityflo.com', lead_type: 'contract', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },
  {
    id: 11, source_table: 'App', prod_id: 50011, name: 'Ritu Kapoor', mobile_number: '9765438901', email: 'ritu.k@gmail.com',
    origin: 'Chembur, Mumbai', destination: 'Matheran', start_date_time: daysFromNow(9), end_date_time: daysFromNow(10),
    number_of_passengers: 7, additional_comment: 'Birthday celebration trip', source: 'app', travel_distance: '80 km', travel_time: '2h',
    vehicle_type_requirement: 'Innova Crysta', status: 'Quote Shared', reason: null, internal_remarks: 'Sent quote ₹12K. Customer comparing with Ola Outstation.',
    amount_quote: 12000, amount_cityflo: 10000, amount_operator: null, operator_name: null,
    created: daysAgo(2), modified: hoursAgo(16), created_by_email_id: null,
    assigned_to_email_id: 'priya.mehta@cityflo.com', lead_type: 'round-trip', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },

  // === QUOTE SHARED — stale (>3 days) ===
  {
    id: 12, source_table: 'Meta', prod_id: 50012, name: 'Sanjay Verma', mobile_number: '9654321876', email: null,
    origin: 'Kalyan, Mumbai', destination: 'Aurangabad (Ajanta Caves)', start_date_time: daysFromNow(12), end_date_time: daysFromNow(13),
    number_of_passengers: 10, additional_comment: null, source: 'Meta', travel_distance: '330 km', travel_time: '6h',
    vehicle_type_requirement: 'Tempo Traveller', status: 'Quote Shared', reason: null, internal_remarks: 'Quote sent 5 days ago. No response on calls/WhatsApp.',
    amount_quote: 28000, amount_cityflo: 24000, amount_operator: null, operator_name: null,
    created: daysAgo(6), modified: daysAgo(5), created_by_email_id: null,
    assigned_to_email_id: 'rahul.gupta@cityflo.com', lead_type: 'round-trip', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },
  {
    id: 13, source_table: 'Web', prod_id: 50013, name: 'Anjali Bhatt', mobile_number: '9543217654', email: 'anjali.b@startup.io',
    origin: 'Goregaon, Mumbai', destination: 'Imagicaa (Khopoli)', start_date_time: daysFromNow(3), end_date_time: daysFromNow(3),
    number_of_passengers: 25, additional_comment: 'Company fun day', source: 'website', travel_distance: '75 km', travel_time: '1.5h',
    vehicle_type_requirement: 'Bus 32-seater', status: 'Quote Shared', reason: null, internal_remarks: 'Sent revised quote 4 days ago after negotiation. Waiting.',
    amount_quote: 45000, amount_cityflo: 38000, amount_operator: null, operator_name: null,
    created: daysAgo(7), modified: daysAgo(4), created_by_email_id: null,
    assigned_to_email_id: 'satveer.singh@cityflo.com', lead_type: 'round-trip', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },

  // === CONVERTED ===
  {
    id: 14, source_table: 'App', prod_id: 50014, name: 'Meera Iyer', mobile_number: '9432165487', email: 'meera.i@gmail.com',
    origin: 'Mulund, Mumbai', destination: 'Bhimashankar', start_date_time: daysFromNow(3), end_date_time: daysFromNow(3),
    number_of_passengers: 5, additional_comment: null, source: 'app', travel_distance: '110 km', travel_time: '3h',
    vehicle_type_requirement: 'Innova', status: 'Converted', reason: null, internal_remarks: 'Confirmed and paid advance',
    amount_quote: 22000, amount_cityflo: 20000, amount_operator: 18000, operator_name: 'Sharma Travels',
    created: daysAgo(5), modified: daysAgo(1), created_by_email_id: null,
    assigned_to_email_id: 'vaibhavi.salvi@cityflo.com', lead_type: 'round-trip', ops_assignee: 'rahul.gupta@cityflo.com',
    payment_remark: 'Advance ₹10K received', customer_paid_amount: 10000, payment_mode: 'UPI', payment_status: 'Partial',
    balance_remark: 'Balance ₹12K on trip day', invoice_number: null, invoice_date: null, gst_aadhaar_number: '4567 8901 2345',
    operators: ops[14],
  },
  {
    id: 15, source_table: 'Web', prod_id: 50015, name: 'TechCorp Solutions Pvt Ltd', mobile_number: '9321654987', email: 'admin@techcorp.in',
    origin: 'BKC, Mumbai', destination: 'Pune (Magarpatta)', start_date_time: daysAgo(2), end_date_time: daysAgo(1),
    number_of_passengers: 50, additional_comment: 'Annual offsite - 2 luxury buses', source: 'website', travel_distance: '150 km', travel_time: '3h',
    vehicle_type_requirement: 'Luxury Bus (2)', status: 'Converted', reason: null, internal_remarks: 'Trip completed. Invoiced.',
    amount_quote: 120000, amount_cityflo: 100000, amount_operator: 70000, operator_name: 'Patel Tours',
    created: daysAgo(15), modified: daysAgo(1), created_by_email_id: null,
    assigned_to_email_id: 'satveer.singh@cityflo.com', lead_type: 'round-trip', ops_assignee: 'priya.mehta@cityflo.com',
    payment_remark: 'Full payment received via NEFT', customer_paid_amount: 120000, payment_mode: 'Bank Transfer', payment_status: 'Received',
    balance_remark: null, invoice_number: 'INV-2026-0234', invoice_date: '2026-02-22', gst_aadhaar_number: '27AABCT1234F1Z5',
    operators: ops[15],
  },
  {
    id: 16, source_table: 'Meta', prod_id: 50016, name: 'Rohit Saxena', mobile_number: '9210987654', email: 'rohit.s@gmail.com',
    origin: 'Versova, Mumbai', destination: 'Tarkarli Beach', start_date_time: daysFromNow(1), end_date_time: daysFromNow(3),
    number_of_passengers: 8, additional_comment: 'Scuba diving trip', source: 'Meta', travel_distance: '480 km', travel_time: '9h',
    vehicle_type_requirement: 'Tempo Traveller', status: 'Converted', reason: null, internal_remarks: 'Confirmed. Bus departs tomorrow 6 AM.',
    amount_quote: 35000, amount_cityflo: 30000, amount_operator: 22000, operator_name: 'Gupta Transport',
    created: daysAgo(8), modified: hoursAgo(6), created_by_email_id: null,
    assigned_to_email_id: 'rahul.gupta@cityflo.com', lead_type: 'round-trip', ops_assignee: 'satveer.singh@cityflo.com',
    payment_remark: 'Advance received', customer_paid_amount: 20000, payment_mode: 'UPI', payment_status: 'Partial',
    balance_remark: '₹15K balance on return', invoice_number: null, invoice_date: null, gst_aadhaar_number: '27AADCS5678G1Z3',
    operators: ops[16],
  },
  {
    id: 17, source_table: 'App', prod_id: 50017, name: 'Lakshmi Rao', mobile_number: '9109876543', email: 'lakshmi.r@yahoo.com',
    origin: 'Navi Mumbai', destination: 'Panchgani', start_date_time: daysFromNow(6), end_date_time: daysFromNow(7),
    number_of_passengers: 4, additional_comment: null, source: 'referral', travel_distance: '250 km', travel_time: '5h',
    vehicle_type_requirement: 'Sedan', status: 'Converted', reason: null, internal_remarks: 'Converted but payment not yet received',
    amount_quote: 15000, amount_cityflo: 13000, amount_operator: null, operator_name: null,
    created: daysAgo(3), modified: daysAgo(1), created_by_email_id: null,
    assigned_to_email_id: 'vaibhavi.salvi@cityflo.com', lead_type: 'round-trip', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: 'Pending',
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null,
    operators: ops[17],
  },

  // === CLOSED ===
  {
    id: 18, source_table: 'Meta', prod_id: 50018, name: 'Yashwant Rane', mobile_number: '9098765432', email: null,
    origin: 'Panvel', destination: 'Ratnagiri', start_date_time: daysAgo(1), end_date_time: daysAgo(1),
    number_of_passengers: 6, additional_comment: null, source: 'Meta', travel_distance: '330 km', travel_time: '6h',
    vehicle_type_requirement: 'Innova', status: 'Closed', reason: 'Budget too high', internal_remarks: 'Customer wanted ₹8K for Ratnagiri round trip. Not feasible.',
    amount_quote: 18000, amount_cityflo: null, amount_operator: null, operator_name: null,
    created: daysAgo(5), modified: daysAgo(1), created_by_email_id: null,
    assigned_to_email_id: 'satveer.singh@cityflo.com', lead_type: 'round-trip', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },
  {
    id: 19, source_table: 'Web', prod_id: 50019, name: 'Prashant Gokhale', mobile_number: '9987654301', email: 'prashant.g@gmail.com',
    origin: 'Kandivali, Mumbai', destination: 'Surat', start_date_time: daysAgo(3), end_date_time: daysAgo(2),
    number_of_passengers: 3, additional_comment: null, source: 'website', travel_distance: '280 km', travel_time: '5h',
    vehicle_type_requirement: 'Sedan', status: 'Closed', reason: 'Chose competitor', internal_remarks: 'Went with Savaari. Their quote was ₹2K lower.',
    amount_quote: 14000, amount_cityflo: null, amount_operator: null, operator_name: null,
    created: daysAgo(8), modified: daysAgo(3), created_by_email_id: null,
    assigned_to_email_id: 'priya.mehta@cityflo.com', lead_type: 'one-way', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },
  {
    id: 20, source_table: 'App', prod_id: 50020, name: 'Divya Nambiar', mobile_number: '9876501234', email: 'divya.n@outlook.com',
    origin: 'Andheri West, Mumbai', destination: 'Udaipur', start_date_time: daysAgo(2), end_date_time: daysAgo(1),
    number_of_passengers: 2, additional_comment: null, source: 'app', travel_distance: '770 km', travel_time: '12h',
    vehicle_type_requirement: 'Sedan', status: 'Closed', reason: 'Trip cancelled', internal_remarks: 'Personal emergency. May rebook later.',
    amount_quote: 25000, amount_cityflo: null, amount_operator: null, operator_name: null,
    created: daysAgo(10), modified: daysAgo(2), created_by_email_id: null,
    assigned_to_email_id: 'rahul.gupta@cityflo.com', lead_type: 'one-way', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },

  // === More OPEN for variety ===
  {
    id: 23, source_table: 'Web', prod_id: 50023, name: 'Tanvi Mehta', mobile_number: '9432109876', email: 'tanvi@startup.co',
    origin: 'Fort, Mumbai', destination: 'Alibag (Mandwa Jetty)', start_date_time: daysFromNow(4), end_date_time: daysFromNow(4),
    number_of_passengers: 15, additional_comment: 'Startup team outing', source: 'website', travel_distance: '95 km', travel_time: '2.5h',
    vehicle_type_requirement: 'Tempo Traveller', status: 'Open', reason: null, internal_remarks: null,
    amount_quote: null, amount_cityflo: null, amount_operator: null, operator_name: null,
    created: hoursAgo(1), modified: hoursAgo(1), created_by_email_id: null,
    assigned_to_email_id: 'vaibhavi.salvi@cityflo.com', lead_type: 'round-trip', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },
  {
    id: 24, source_table: 'Meta', prod_id: 50024, name: 'Ibrahim Patel', mobile_number: '9321098765', email: null,
    origin: 'Kurla, Mumbai', destination: 'Solapur', start_date_time: daysFromNow(6), end_date_time: daysFromNow(7),
    number_of_passengers: 3, additional_comment: 'Business meeting', source: 'Meta', travel_distance: '400 km', travel_time: '7h',
    vehicle_type_requirement: 'Sedan', status: 'Open', reason: null, internal_remarks: null,
    amount_quote: null, amount_cityflo: null, amount_operator: null, operator_name: null,
    created: hoursAgo(12), modified: hoursAgo(12), created_by_email_id: null,
    assigned_to_email_id: 'satveer.singh@cityflo.com', lead_type: 'one-way', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },
  {
    id: 25, source_table: 'App', prod_id: 50025, name: 'Shreya Jain', mobile_number: '9210987600', email: 'shreya.j@gmail.com',
    origin: 'Vikhroli, Mumbai', destination: 'Mahad (Rafting)', start_date_time: daysFromNow(8), end_date_time: daysFromNow(8),
    number_of_passengers: 12, additional_comment: 'Adventure group, need a TT with good suspension', source: 'app', travel_distance: '155 km', travel_time: '3.5h',
    vehicle_type_requirement: 'Tempo Traveller', status: 'Quote Shared', reason: null, internal_remarks: 'Sent ₹20K quote. Comparing with local operator.',
    amount_quote: 20000, amount_cityflo: 17000, amount_operator: null, operator_name: null,
    created: daysAgo(2), modified: hoursAgo(10), created_by_email_id: null,
    assigned_to_email_id: 'priya.mehta@cityflo.com', lead_type: 'round-trip', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },

  // === NEW CONVERTED LEADS ===
  {
    id: 26, source_table: 'Web', prod_id: 50026, name: 'Arjun Kapoor', mobile_number: '9876012345', email: 'arjun.k@techfirm.com',
    origin: 'Andheri West, Mumbai', destination: 'Lonavala (Della Resort)', start_date_time: daysFromNow(2), end_date_time: daysFromNow(3),
    number_of_passengers: 10, additional_comment: 'Team offsite, pick up from office', source: 'website', travel_distance: '85 km', travel_time: '2h',
    vehicle_type_requirement: 'Tempo Traveller', status: 'Converted', reason: null, internal_remarks: 'Confirmed. Pickup at 7 AM.',
    amount_quote: 35000, amount_cityflo: 30000, amount_operator: 25000, operator_name: 'Rebello',
    created: daysAgo(6), modified: daysAgo(2), created_by_email_id: null,
    assigned_to_email_id: 'priya.mehta@cityflo.com', lead_type: 'round-trip', ops_assignee: 'satveer.singh@cityflo.com',
    payment_remark: 'Full payment received via UPI', customer_paid_amount: 35000, payment_mode: 'UPI', payment_status: 'Received',
    balance_remark: null, invoice_number: 'INV-2026-0240', invoice_date: '2026-02-28', gst_aadhaar_number: null,
    operators: ops[26],
  },
  {
    id: 27, source_table: 'App', prod_id: 50027, name: 'Neha Sharma', mobile_number: '9765098712', email: 'neha.s@gmail.com',
    origin: 'Dadar, Mumbai', destination: 'Khandala', start_date_time: daysFromNow(4), end_date_time: daysFromNow(4),
    number_of_passengers: 4, additional_comment: 'Family trip with elderly parents', source: 'app', travel_distance: '80 km', travel_time: '2h',
    vehicle_type_requirement: 'Innova Crysta', status: 'Converted', reason: null, internal_remarks: 'Confirmed. AC must work well.',
    amount_quote: 18000, amount_cityflo: 16000, amount_operator: 14000, operator_name: 'Surya Travels',
    created: daysAgo(4), modified: daysAgo(1), created_by_email_id: null,
    assigned_to_email_id: 'vaibhavi.salvi@cityflo.com', lead_type: 'round-trip', ops_assignee: 'rahul.gupta@cityflo.com',
    payment_remark: 'Advance ₹8K', customer_paid_amount: 8000, payment_mode: 'UPI', payment_status: 'Partial',
    balance_remark: 'Balance on day of trip', invoice_number: null, invoice_date: null, gst_aadhaar_number: '5678 1234 9012',
    operators: ops[27],
  },
  {
    id: 28, source_table: 'Web', prod_id: 50028, name: 'Global Infotech Ltd', mobile_number: '9654012378', email: 'hr@globalinfotech.in',
    origin: 'Lower Parel, Mumbai', destination: 'Goa (Calangute)', start_date_time: daysAgo(3), end_date_time: daysAgo(1),
    number_of_passengers: 45, additional_comment: 'Annual reward trip - 2 AC buses', source: 'website', travel_distance: '590 km', travel_time: '10h',
    vehicle_type_requirement: 'Bus (2)', status: 'Converted', reason: null, internal_remarks: 'Trip completed. Invoice pending.',
    amount_quote: 150000, amount_cityflo: 130000, amount_operator: 85000, operator_name: 'Indian Travels',
    created: daysAgo(20), modified: daysAgo(1), created_by_email_id: null,
    assigned_to_email_id: 'satveer.singh@cityflo.com', lead_type: 'round-trip', ops_assignee: 'priya.mehta@cityflo.com',
    payment_remark: 'Partial advance received, balance post-trip', customer_paid_amount: 100000, payment_mode: 'Bank Transfer', payment_status: 'Partial',
    balance_remark: '₹50K balance due', invoice_number: 'INV-2026-0238', invoice_date: '2026-02-27', gst_aadhaar_number: '27AABCG9876D1Z2',
    operators: ops[28],
  },
  {
    id: 29, source_table: 'App', prod_id: 50029, name: 'Priya Deshpande', mobile_number: '9543098761', email: 'priya.d@outlook.com',
    origin: 'Thane, Mumbai', destination: 'Matheran', start_date_time: daysFromNow(1), end_date_time: daysFromNow(1),
    number_of_passengers: 3, additional_comment: 'Drop at Dasturi Naka', source: 'app', travel_distance: '80 km', travel_time: '2h',
    vehicle_type_requirement: 'Sedan', status: 'Converted', reason: null, internal_remarks: 'Small trip, confirmed for tomorrow.',
    amount_quote: 10000, amount_cityflo: 9000, amount_operator: 8000, operator_name: 'GHAPL',
    created: daysAgo(3), modified: hoursAgo(5), created_by_email_id: null,
    assigned_to_email_id: 'rahul.gupta@cityflo.com', lead_type: 'one-way', ops_assignee: 'vaibhavi.salvi@cityflo.com',
    payment_remark: 'Full advance', customer_paid_amount: 10000, payment_mode: 'UPI', payment_status: 'Received',
    balance_remark: null, invoice_number: 'INV-2026-0241', invoice_date: '2026-03-01', gst_aadhaar_number: null,
    operators: ops[29],
  },
  {
    id: 30, source_table: 'Meta', prod_id: 50030, name: 'Rajesh Tiwari', mobile_number: '9432076543', email: 'rajesh.t@gmail.com',
    origin: 'Mulund, Mumbai', destination: 'Nashik (Sula Vineyards)', start_date_time: daysFromNow(5), end_date_time: daysFromNow(6),
    number_of_passengers: 6, additional_comment: 'Wine tasting weekend', source: 'Meta', travel_distance: '170 km', travel_time: '3.5h',
    vehicle_type_requirement: 'Innova Crysta', status: 'Converted', reason: null, internal_remarks: 'Confirmed. Wants early morning departure.',
    amount_quote: 22000, amount_cityflo: 19000, amount_operator: 16000, operator_name: 'Dwarikamai',
    created: daysAgo(5), modified: daysAgo(2), created_by_email_id: null,
    assigned_to_email_id: 'vaibhavi.salvi@cityflo.com', lead_type: 'round-trip', ops_assignee: 'satveer.singh@cityflo.com',
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: 'Pending',
    balance_remark: 'Payment due before trip', invoice_number: null, invoice_date: null, gst_aadhaar_number: null,
    operators: ops[30],
  },
  {
    id: 31, source_table: 'Web', prod_id: 50031, name: 'MegaCorp Industries', mobile_number: '9321065432', email: 'admin@megacorp.co.in',
    origin: 'BKC, Mumbai', destination: 'Shirdi + Shani Shingnapur', start_date_time: daysAgo(6), end_date_time: daysAgo(4),
    number_of_passengers: 35, additional_comment: 'Employee pilgrimage trip', source: 'website', travel_distance: '240 km', travel_time: '5h',
    vehicle_type_requirement: 'Luxury Bus', status: 'Converted', reason: null, internal_remarks: 'Trip completed successfully. Very positive feedback.',
    amount_quote: 80000, amount_cityflo: 70000, amount_operator: 55000, operator_name: 'Ajara Travels',
    created: daysAgo(18), modified: daysAgo(4), created_by_email_id: null,
    assigned_to_email_id: 'priya.mehta@cityflo.com', lead_type: 'round-trip', ops_assignee: 'rahul.gupta@cityflo.com',
    payment_remark: 'Full payment received', customer_paid_amount: 80000, payment_mode: 'Bank Transfer', payment_status: 'Received',
    balance_remark: null, invoice_number: 'INV-2026-0235', invoice_date: '2026-02-24', gst_aadhaar_number: '27AAECM4567H1Z8',
    operators: ops[31],
  },
  {
    id: 32, source_table: 'App', prod_id: 50032, name: 'Sameer Kulkarni', mobile_number: '9210054321', email: 'sameer.k@yahoo.com',
    origin: 'Panvel, Navi Mumbai', destination: 'Mahabaleshwar', start_date_time: daysFromNow(3), end_date_time: daysFromNow(4),
    number_of_passengers: 8, additional_comment: 'Anniversary trip, need good vehicle', source: 'referral', travel_distance: '230 km', travel_time: '5h',
    vehicle_type_requirement: 'Tempo Traveller', status: 'Converted', reason: null, internal_remarks: 'Referred by Arjun Kapoor (lead 26). Confirmed.',
    amount_quote: 28000, amount_cityflo: 24000, amount_operator: 20000, operator_name: 'Siddhant Travels',
    created: daysAgo(4), modified: daysAgo(1), created_by_email_id: null,
    assigned_to_email_id: 'rahul.gupta@cityflo.com', lead_type: 'round-trip', ops_assignee: 'priya.mehta@cityflo.com',
    payment_remark: 'Advance ₹14K', customer_paid_amount: 14000, payment_mode: 'Bank Transfer', payment_status: 'Partial',
    balance_remark: '₹14K on trip day', invoice_number: null, invoice_date: null, gst_aadhaar_number: null,
    operators: ops[32],
  },
  {
    id: 33, source_table: 'Meta', prod_id: 50033, name: 'Aarti Joshi', mobile_number: '9109043210', email: 'aarti.j@company.com',
    origin: 'Powai, Mumbai', destination: 'Pune (Koregaon Park)', start_date_time: daysFromNow(7), end_date_time: daysFromNow(7),
    number_of_passengers: 4, additional_comment: null, source: 'Meta', travel_distance: '150 km', travel_time: '3h',
    vehicle_type_requirement: 'Sedan', status: 'Converted', reason: null, internal_remarks: 'Confirmed. Payment pending.',
    amount_quote: 12000, amount_cityflo: 10000, amount_operator: null, operator_name: null,
    created: daysAgo(3), modified: daysAgo(1), created_by_email_id: null,
    assigned_to_email_id: 'satveer.singh@cityflo.com', lead_type: 'one-way', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: 'Pending',
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null,
    operators: ops[33],
  },

  // === NEW OPEN LEADS ===
  {
    id: 34, source_table: 'App', prod_id: 50034, name: 'Vivek Choudhary', mobile_number: '9876123400', email: 'vivek.c@gmail.com',
    origin: 'Kandivali West, Mumbai', destination: 'Daman', start_date_time: daysFromNow(6), end_date_time: daysFromNow(7),
    number_of_passengers: 6, additional_comment: 'Friends trip, budget conscious', source: 'app', travel_distance: '170 km', travel_time: '3.5h',
    vehicle_type_requirement: 'Innova', status: 'Open', reason: null, internal_remarks: null,
    amount_quote: null, amount_cityflo: null, amount_operator: null, operator_name: null,
    created: hoursAgo(2), modified: hoursAgo(2), created_by_email_id: null,
    assigned_to_email_id: 'rahul.gupta@cityflo.com', lead_type: 'round-trip', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },
  {
    id: 35, source_table: 'Meta', prod_id: 50035, name: 'Geeta Nair', mobile_number: '9765112233', email: null,
    origin: 'Chembur, Mumbai', destination: 'Kolad (Rafting)', start_date_time: daysFromNow(3), end_date_time: daysFromNow(3),
    number_of_passengers: 14, additional_comment: 'College group, need affordable TT', source: 'Meta', travel_distance: '120 km', travel_time: '3h',
    vehicle_type_requirement: 'Tempo Traveller', status: 'Open', reason: null, internal_remarks: null,
    amount_quote: null, amount_cityflo: null, amount_operator: null, operator_name: null,
    created: hoursAgo(5), modified: hoursAgo(5), created_by_email_id: null,
    assigned_to_email_id: 'satveer.singh@cityflo.com', lead_type: 'round-trip', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },
  {
    id: 36, source_table: 'Web', prod_id: 50036, name: 'Sunil Patil', mobile_number: '9654223344', email: 'sunil.p@firm.co',
    origin: 'Worli, Mumbai', destination: 'Alibaug (Nagaon Beach)', start_date_time: daysFromNow(5), end_date_time: daysFromNow(5),
    number_of_passengers: 20, additional_comment: 'Office picnic, need large bus', source: 'website', travel_distance: '100 km', travel_time: '2.5h',
    vehicle_type_requirement: 'Bus 32-seater', status: 'Open', reason: null, internal_remarks: null,
    amount_quote: null, amount_cityflo: null, amount_operator: null, operator_name: null,
    created: hoursAgo(8), modified: hoursAgo(8), created_by_email_id: null,
    assigned_to_email_id: 'priya.mehta@cityflo.com', lead_type: 'round-trip', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },
  {
    id: 37, source_table: 'App', prod_id: 50037, name: 'Ananya Rao', mobile_number: '9543334455', email: 'ananya.r@gmail.com',
    origin: 'Goregaon East, Mumbai', destination: 'Pune Airport', start_date_time: daysFromNow(1), end_date_time: daysFromNow(1),
    number_of_passengers: 2, additional_comment: 'Early morning flight, need 4 AM pickup', source: 'app', travel_distance: '150 km', travel_time: '3h',
    vehicle_type_requirement: 'Sedan', status: 'Open', reason: null, internal_remarks: null,
    amount_quote: null, amount_cityflo: null, amount_operator: null, operator_name: null,
    created: hoursAgo(1), modified: hoursAgo(1), created_by_email_id: null,
    assigned_to_email_id: 'vaibhavi.salvi@cityflo.com', lead_type: 'one-way', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },

  // === NEW CONTACTED LEADS ===
  {
    id: 38, source_table: 'Meta', prod_id: 50038, name: 'Kiran Bhagat', mobile_number: '9432445566', email: 'kiran.b@techcorp.in',
    origin: 'Bandra East, Mumbai', destination: 'Igatpuri (camping)', start_date_time: daysFromNow(8), end_date_time: daysFromNow(9),
    number_of_passengers: 18, additional_comment: 'Corporate team building, 2 day event', source: 'Meta', travel_distance: '130 km', travel_time: '2.5h',
    vehicle_type_requirement: 'Tempo Traveller', status: 'Contacted', reason: null, internal_remarks: 'Discussed requirements. Wants TT with pushback seats.',
    amount_quote: null, amount_cityflo: null, amount_operator: null, operator_name: null,
    created: daysAgo(1), modified: hoursAgo(6), created_by_email_id: null,
    assigned_to_email_id: 'vaibhavi.salvi@cityflo.com', lead_type: 'round-trip', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },
  {
    id: 39, source_table: 'App', prod_id: 50039, name: 'Harish Menon', mobile_number: '9321556677', email: null,
    origin: 'Vashi, Navi Mumbai', destination: 'Ganpatipule', start_date_time: daysFromNow(10), end_date_time: daysFromNow(12),
    number_of_passengers: 8, additional_comment: 'Temple visit + beach holiday', source: 'app', travel_distance: '350 km', travel_time: '7h',
    vehicle_type_requirement: 'Innova Crysta', status: 'Contacted', reason: null, internal_remarks: 'Called twice, interested but checking dates with family.',
    amount_quote: null, amount_cityflo: null, amount_operator: null, operator_name: null,
    created: daysAgo(2), modified: hoursAgo(20), created_by_email_id: null,
    assigned_to_email_id: 'rahul.gupta@cityflo.com', lead_type: 'round-trip', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },
  {
    id: 40, source_table: 'Web', prod_id: 50040, name: 'Madhavi Deshmukh', mobile_number: '9210667788', email: 'madhavi.d@startup.io',
    origin: 'Hinjewadi, Pune', destination: 'Mumbai Airport (T2)', start_date_time: daysFromNow(2), end_date_time: daysFromNow(2),
    number_of_passengers: 3, additional_comment: 'Flight at 8 PM, need late afternoon pickup', source: 'website', travel_distance: '150 km', travel_time: '3h',
    vehicle_type_requirement: 'Sedan', status: 'Contacted', reason: null, internal_remarks: 'WhatsApp conversation. Waiting for exact pickup time.',
    amount_quote: null, amount_cityflo: null, amount_operator: null, operator_name: null,
    created: daysAgo(1), modified: hoursAgo(3), created_by_email_id: null,
    assigned_to_email_id: 'priya.mehta@cityflo.com', lead_type: 'one-way', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },
  {
    id: 41, source_table: 'Meta', prod_id: 50041, name: 'Rahul Sawant', mobile_number: '9109778899', email: 'rahul.sawant@gmail.com',
    origin: 'Kalyan, Mumbai', destination: 'Bhandardara (Lake)', start_date_time: daysFromNow(4), end_date_time: daysFromNow(5),
    number_of_passengers: 10, additional_comment: 'Camping trip with adventure activities', source: 'Meta', travel_distance: '160 km', travel_time: '4h',
    vehicle_type_requirement: 'Tempo Traveller', status: 'Contacted', reason: null, internal_remarks: 'High interest. Wants to know if TT can handle off-road.',
    amount_quote: null, amount_cityflo: null, amount_operator: null, operator_name: null,
    created: daysAgo(3), modified: daysAgo(2), created_by_email_id: null,
    assigned_to_email_id: 'satveer.singh@cityflo.com', lead_type: 'round-trip', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },

  // === NEW QUOTE SHARED LEADS ===
  {
    id: 42, source_table: 'Web', prod_id: 50042, name: 'Devika Pillai', mobile_number: '9876889900', email: 'devika.p@enterprise.com',
    origin: 'Fort, Mumbai', destination: 'Tapola (Mini Kashmir)', start_date_time: daysFromNow(9), end_date_time: daysFromNow(11),
    number_of_passengers: 16, additional_comment: 'Leadership offsite, premium vehicle required', source: 'website', travel_distance: '280 km', travel_time: '6h',
    vehicle_type_requirement: 'Luxury Bus', status: 'Quote Shared', reason: null, internal_remarks: 'Shared ₹65K quote. They want to compare with 2 other vendors.',
    amount_quote: 65000, amount_cityflo: 55000, amount_operator: null, operator_name: null,
    created: daysAgo(3), modified: hoursAgo(12), created_by_email_id: null,
    assigned_to_email_id: 'vaibhavi.salvi@cityflo.com', lead_type: 'round-trip', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },
  {
    id: 43, source_table: 'App', prod_id: 50043, name: 'Mohan Gupta', mobile_number: '9765990011', email: 'mohan.g@yahoo.com',
    origin: 'Borivali, Mumbai', destination: 'Saputara', start_date_time: daysFromNow(7), end_date_time: daysFromNow(8),
    number_of_passengers: 7, additional_comment: 'Hill station trip', source: 'app', travel_distance: '220 km', travel_time: '5h',
    vehicle_type_requirement: 'Innova Crysta', status: 'Quote Shared', reason: null, internal_remarks: 'Sent ₹18K quote. Customer says will confirm by tomorrow.',
    amount_quote: 18000, amount_cityflo: 15000, amount_operator: null, operator_name: null,
    created: daysAgo(2), modified: hoursAgo(4), created_by_email_id: null,
    assigned_to_email_id: 'rahul.gupta@cityflo.com', lead_type: 'round-trip', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },
  {
    id: 44, source_table: 'Meta', prod_id: 50044, name: 'Nandini Shah', mobile_number: '9654001122', email: 'nandini.s@gmail.com',
    origin: 'Malad, Mumbai', destination: 'Alibaug (Beach Resort)', start_date_time: daysFromNow(3), end_date_time: daysFromNow(3),
    number_of_passengers: 22, additional_comment: 'Sangeet ceremony, need decorated bus', source: 'Meta', travel_distance: '100 km', travel_time: '2.5h',
    vehicle_type_requirement: 'Bus 32-seater', status: 'Quote Shared', reason: null, internal_remarks: 'Sent ₹40K. Negotiating — wants ₹35K.',
    amount_quote: 40000, amount_cityflo: 35000, amount_operator: null, operator_name: null,
    created: daysAgo(4), modified: daysAgo(1), created_by_email_id: null,
    assigned_to_email_id: 'satveer.singh@cityflo.com', lead_type: 'round-trip', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },

  // === NEW CLOSED LEADS ===
  {
    id: 45, source_table: 'Web', prod_id: 50045, name: 'Siddharth Rane', mobile_number: '9543112233', email: 'sid.rane@gmail.com',
    origin: 'Thane, Mumbai', destination: 'Aurangabad (Ellora Caves)', start_date_time: daysAgo(2), end_date_time: daysAgo(1),
    number_of_passengers: 5, additional_comment: null, source: 'website', travel_distance: '330 km', travel_time: '6h',
    vehicle_type_requirement: 'Innova', status: 'Closed', reason: 'No response', internal_remarks: 'Called 5 times, no pickup. WhatsApp messages seen but no reply.',
    amount_quote: 22000, amount_cityflo: null, amount_operator: null, operator_name: null,
    created: daysAgo(10), modified: daysAgo(2), created_by_email_id: null,
    assigned_to_email_id: 'vaibhavi.salvi@cityflo.com', lead_type: 'round-trip', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },
  {
    id: 46, source_table: 'Meta', prod_id: 50046, name: 'Alok Mishra', mobile_number: '9432223344', email: null,
    origin: 'Bhandup, Mumbai', destination: 'Nashik', start_date_time: daysAgo(4), end_date_time: daysAgo(3),
    number_of_passengers: 4, additional_comment: null, source: 'Meta', travel_distance: '170 km', travel_time: '3.5h',
    vehicle_type_requirement: 'Sedan', status: 'Closed', reason: 'Budget too high', internal_remarks: 'Wanted sedan for ₹5K. Our minimum is ₹10K.',
    amount_quote: 10000, amount_cityflo: null, amount_operator: null, operator_name: null,
    created: daysAgo(8), modified: daysAgo(4), created_by_email_id: null,
    assigned_to_email_id: 'priya.mehta@cityflo.com', lead_type: 'round-trip', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },
  {
    id: 47, source_table: 'App', prod_id: 50047, name: 'Sheetal Wagh', mobile_number: '9321334455', email: 'sheetal.w@outlook.com',
    origin: 'Navi Mumbai', destination: 'Pune (Hadapsar)', start_date_time: daysAgo(1), end_date_time: daysAgo(1),
    number_of_passengers: 2, additional_comment: null, source: 'app', travel_distance: '150 km', travel_time: '3h',
    vehicle_type_requirement: 'Sedan', status: 'Closed', reason: 'Chose competitor', internal_remarks: 'Booked with RedBus rentals. ₹1.5K cheaper.',
    amount_quote: 8000, amount_cityflo: null, amount_operator: null, operator_name: null,
    created: daysAgo(5), modified: daysAgo(1), created_by_email_id: null,
    assigned_to_email_id: 'rahul.gupta@cityflo.com', lead_type: 'one-way', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },
  {
    id: 48, source_table: 'direct', prod_id: null, name: 'Vijay Thakur', mobile_number: '9210445566', email: null,
    origin: 'Vasai, Mumbai', destination: 'Silvassa', start_date_time: daysAgo(3), end_date_time: daysAgo(2),
    number_of_passengers: 30, additional_comment: 'Factory visit', source: 'direct call', travel_distance: '120 km', travel_time: '2.5h',
    vehicle_type_requirement: 'Bus 32-seater', status: 'Closed', reason: 'Trip cancelled', internal_remarks: 'Factory visit postponed indefinitely.',
    amount_quote: 35000, amount_cityflo: null, amount_operator: null, operator_name: null,
    created: daysAgo(12), modified: daysAgo(3), created_by_email_id: null,
    assigned_to_email_id: 'satveer.singh@cityflo.com', lead_type: 'round-trip', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },

  // === NOT RESPONDED LEADS ===
  {
    id: 49, source_table: 'Meta', prod_id: 50049, name: 'Poornima Kadam', mobile_number: '9109556677', email: null,
    origin: 'Dombivli, Mumbai', destination: 'Unknown', start_date_time: daysFromNow(5), end_date_time: daysFromNow(5),
    number_of_passengers: null, additional_comment: 'Enquired via Meta form, incomplete details', source: 'Meta', travel_distance: null, travel_time: null,
    vehicle_type_requirement: null, status: 'Not Responded', reason: null, internal_remarks: 'Phone switched off. Will retry.',
    amount_quote: null, amount_cityflo: null, amount_operator: null, operator_name: null,
    created: daysAgo(2), modified: daysAgo(2), created_by_email_id: null,
    assigned_to_email_id: 'vaibhavi.salvi@cityflo.com', lead_type: null, ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },
  {
    id: 50, source_table: 'Meta', prod_id: 50050, name: 'Tushar Pawar', mobile_number: '9876667788', email: null,
    origin: 'Ambernath', destination: 'Shirdi', start_date_time: daysFromNow(6), end_date_time: daysFromNow(6),
    number_of_passengers: 6, additional_comment: null, source: 'Meta', travel_distance: '230 km', travel_time: '5h',
    vehicle_type_requirement: 'Innova', status: 'Not Responded', reason: null, internal_remarks: 'Number busy. Left WhatsApp message.',
    amount_quote: null, amount_cityflo: null, amount_operator: null, operator_name: null,
    created: daysAgo(1), modified: daysAgo(1), created_by_email_id: null,
    assigned_to_email_id: 'priya.mehta@cityflo.com', lead_type: 'round-trip', ops_assignee: null,
    payment_remark: null, customer_paid_amount: null, payment_mode: null, payment_status: null,
    balance_remark: null, invoice_number: null, invoice_date: null, gst_aadhaar_number: null, operators: [],
  },
]

// Simulated logs for some leads
export const DUMMY_LOGS: Record<number, Array<{
  id: number | null; status: string | null; assigned_to_email_id: string | null;
  modified: string | null; amount_quote: number | null; amount_cityflo: number | null;
  amount_operator: number | null; operator_name: string | null; reason: string | null; internal_remarks: string | null;
}>> = {
  14: [
    { id: 14, status: 'Quote Shared', assigned_to_email_id: 'priya.mehta@cityflo.com', modified: daysAgo(3), amount_quote: 22000, amount_cityflo: 20000, amount_operator: null, operator_name: null, reason: null, internal_remarks: 'Customer agreed to quote' },
    { id: 14, status: 'Contacted', assigned_to_email_id: 'priya.mehta@cityflo.com', modified: daysAgo(4), amount_quote: null, amount_cityflo: null, amount_operator: null, operator_name: null, reason: null, internal_remarks: 'Called customer, discussed requirements' },
    { id: 14, status: 'Open', assigned_to_email_id: 'satveer.singh@cityflo.com', modified: daysAgo(5), amount_quote: null, amount_cityflo: null, amount_operator: null, operator_name: null, reason: null, internal_remarks: null },
  ],
  15: [
    { id: 15, status: 'Converted', assigned_to_email_id: 'satveer.singh@cityflo.com', modified: daysAgo(5), amount_quote: 120000, amount_cityflo: 100000, amount_operator: 70000, operator_name: 'Patel Tours', reason: null, internal_remarks: 'Contract signed' },
    { id: 15, status: 'Quote Shared', assigned_to_email_id: 'satveer.singh@cityflo.com', modified: daysAgo(8), amount_quote: 120000, amount_cityflo: 100000, amount_operator: null, operator_name: null, reason: null, internal_remarks: 'Quote approved by management' },
    { id: 15, status: 'Contacted', assigned_to_email_id: 'satveer.singh@cityflo.com', modified: daysAgo(12), amount_quote: null, amount_cityflo: null, amount_operator: null, operator_name: null, reason: null, internal_remarks: 'Initial discussion with HR team' },
  ],
  18: [
    { id: 18, status: 'Quote Shared', assigned_to_email_id: 'satveer.singh@cityflo.com', modified: daysAgo(2), amount_quote: 18000, amount_cityflo: null, amount_operator: null, operator_name: null, reason: null, internal_remarks: 'Customer says too expensive' },
    { id: 18, status: 'Contacted', assigned_to_email_id: 'satveer.singh@cityflo.com', modified: daysAgo(4), amount_quote: null, amount_cityflo: null, amount_operator: null, operator_name: null, reason: null, internal_remarks: null },
  ],
  26: [
    { id: 26, status: 'Quote Shared', assigned_to_email_id: 'priya.mehta@cityflo.com', modified: daysAgo(4), amount_quote: 35000, amount_cityflo: 30000, amount_operator: null, operator_name: null, reason: null, internal_remarks: 'Sent quote, approved same day' },
    { id: 26, status: 'Contacted', assigned_to_email_id: 'priya.mehta@cityflo.com', modified: daysAgo(5), amount_quote: null, amount_cityflo: null, amount_operator: null, operator_name: null, reason: null, internal_remarks: 'Called HR, discussed requirements' },
  ],
  28: [
    { id: 28, status: 'Quote Shared', assigned_to_email_id: 'satveer.singh@cityflo.com', modified: daysAgo(10), amount_quote: 150000, amount_cityflo: 130000, amount_operator: null, operator_name: null, reason: null, internal_remarks: 'Quote approved after negotiation' },
    { id: 28, status: 'Contacted', assigned_to_email_id: 'satveer.singh@cityflo.com', modified: daysAgo(15), amount_quote: null, amount_cityflo: null, amount_operator: null, operator_name: null, reason: null, internal_remarks: 'Initial call with HR head' },
  ],
  31: [
    { id: 31, status: 'Quote Shared', assigned_to_email_id: 'priya.mehta@cityflo.com', modified: daysAgo(10), amount_quote: 80000, amount_cityflo: 70000, amount_operator: null, operator_name: null, reason: null, internal_remarks: 'Finalized at ₹80K after meeting' },
    { id: 31, status: 'Contacted', assigned_to_email_id: 'priya.mehta@cityflo.com', modified: daysAgo(14), amount_quote: null, amount_cityflo: null, amount_operator: null, operator_name: null, reason: null, internal_remarks: 'Discussed with admin team' },
  ],
}
